### ISSUE TITLE
Support ARM images

### ISSUE THREAD

**Issue by terrytangyuan** [cncf/cncf-fuzzing#91]
I am on a Mac M1 (arm64) and seeing the following when pulling the images:

```
Unable to find image 'gcr.io/oss-fuzz-base/base-runner:latest' locally
latest: Pulling from oss-fuzz-base/base-runner
08c01a0ec47e: Pull complete 
26db2b7fb236: Pull complete 
1f44b92c8dd8: Pull complete 
48a0f87d472e: Pull complete 
987ef13f0fe0: Pull complete 
70c9ed524714: Pull complete 
5ec98123cb3e: Pull complete 
6be990f73bc1: Pull complete 
293df89222b6: Pull complete 
f74545e6eee4: Pull complete 
a9b0edd055b9: Pull complete 
065de64d84f6: Pull complete 
ef7ffe221187: Pull complete 
ee755a457c4d: Pull complete 
Digest: sha256:dde0612a1cefe5fc8fbac9e7046afbbd555553f5392a779ef96fa590bf13e964
Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-runner:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Note that even though this looks just like an warning. I am running into segfaults when trying to test the pulled image.

**Comment by DavidKorczynski** [comment]
This is an OSS-Fuzz issue/fuzzer engine issues. It's not trivial to solve and I probably would not have high hopes for it being solved in the near future. The issue is tracked on the OSS-Fuzz repository in these issues:
- https://github.com/google/oss-fuzz/issues/2295
- https://github.com/google/oss-fuzz/issues/1754

**Comment by terrytangyuan** [comment]
Got it. Thanks! Feel free to close this one here.
